### ISSUE TITLE
Error when checking has_default() on field. (Related to taggit)

### ISSUE THREAD

**Issue by blanchardjeremy** [ccollins/milkman#17]
When calling Milkman on my JournalEntry model

... I get this exception:

```
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/Users/auzigog/Projects/mamaseeds/code/apps/mainsite/management/commands/milkit.py", line 8, in handle
    all_deliveries()
  File "/Users/auzigog/Projects/mamaseeds/code/apps/mainsite/milk.py", line 11, in all_deliveries
    community_milk.deliveries()
  File "/Users/auzigog/Projects/mamaseeds/code/apps/community/milk.py", line 15, in deliveries
    milkman.deliver(JournalEntry, name='Followed User Story', type='story', author=followed_user)
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/milkman/dairy.py", line 177, in deliver
    return truck.deliver(self, **explicit_values)
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/milkman/dairy.py", line 105, in deliver
    self.set_m2m_fields(target, the_milkman, exclude, related_explicit_values)
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/milkman/dairy.py", line 142, in set_m2m_fields
    self.model_class._meta.local_many_to_many, exclude):
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/milkman/dairy.py", line 164, in fields_to_generate
    self.needs_generated_value(f)]
  File "/Users/auzigog/Projects/mamaseeds/env/lib/python2.7/site-packages/milkman/dairy.py", line 167, in needs_generated_value
    return not field.has_default() and not field.blank and not field.null
AttributeError: 'TaggableManager' object has no attribute 'has_default'
```

[Django taggit](https://github.com/alex/django-taggit/) pretends to be a field, but really isn't, so milkman fails.

It would be great if milkman had support for taggit tags. But in the meantime, here is a one liner fix that you can implement.

``` python
# dairy.py
    def needs_generated_value(self, field):
        return hasattr(field, 'has_default') and not field.has_default() and not field.blank and not field.null
```

Hope this can be implemented soon. :)

**Comment by paltman** [comment]
@auzigog Thanks for this report. I'll try to look into it in the next week or two.

**Comment by rizumu** [comment]
hit this error today and the fix worked for me, thanks.

**Comment by blanchardjeremy** [comment]
@paltman Do know if you'll be able to get around to committing this change in the next week or so?

**Comment by blanchardjeremy** [comment]
@paltman just wanted to check in again and see about the chances of having this merged in? I've been using the code change successfully for the past 3 months. I imagine it will only take a minute to push this change to master and bump the version. It would be extra sweet for me to be able to use your repo directly instead of my fork. Let me know what you think!

**Comment by blanchardjeremy** [comment]
Thanks so much @paltman. I appreciate you committing the fix! Happy new year!
